# Generated by Django 3.2 on 2021-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitePrimebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='nome',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
